# Generated by Django 4.2.4 on 2023-08-26 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('diagnostic', models.TextField()),
                ('treatment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.doctor')),
                ('assigned_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sale_type', models.CharField(max_length=256)),
                ('manufacturer', models.CharField(max_length=256)),
                ('salt', models.TextField()),
                ('price', models.CharField(max_length=256)),
                ('quantity', models.PositiveIntegerField(max_length=5)),
                ('uses', models.TextField()),
                ('working', models.TextField()),
                ('side_effect', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'femaile'), ('Othter', 'other')], max_length=256)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('aadhar', models.CharField(max_length=12)),
                ('aabhar', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='case.case')),
                ('medicine', models.ManyToManyField(to='case.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='case.patient'),
        ),
    ]
