# Generated by Django 4.2.4 on 2023-08-26 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_choice_specialization_choices'),
        ('case', '0002_patient_bllod_pressure_patient_height_patient_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.doctor'),
        ),
        migrations.AlterField(
            model_name='case',
            name='diagnostic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
