# Generated by Django 4.2.4 on 2023-08-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_receptionist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialization',
            old_name='choices',
            new_name='choice',
        ),
    ]
